// Generated by gencpp from file motor_node/VelCommunication.msg
// DO NOT EDIT!


#ifndef MOTOR_NODE_MESSAGE_VELCOMMUNICATION_H
#define MOTOR_NODE_MESSAGE_VELCOMMUNICATION_H

#include <ros/service_traits.h>


#include <motor_node/VelCommunicationRequest.h>
#include <motor_node/VelCommunicationResponse.h>


namespace motor_node
{

struct VelCommunication
{

typedef VelCommunicationRequest Request;
typedef VelCommunicationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VelCommunication
} // namespace motor_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motor_node::VelCommunication > {
  static const char* value()
  {
    return "d305ada655a6639621f582c764d323b8";
  }

  static const char* value(const ::motor_node::VelCommunication&) { return value(); }
};

template<>
struct DataType< ::motor_node::VelCommunication > {
  static const char* value()
  {
    return "motor_node/VelCommunication";
  }

  static const char* value(const ::motor_node::VelCommunication&) { return value(); }
};


// service_traits::MD5Sum< ::motor_node::VelCommunicationRequest> should match
// service_traits::MD5Sum< ::motor_node::VelCommunication >
template<>
struct MD5Sum< ::motor_node::VelCommunicationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motor_node::VelCommunication >::value();
  }
  static const char* value(const ::motor_node::VelCommunicationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motor_node::VelCommunicationRequest> should match
// service_traits::DataType< ::motor_node::VelCommunication >
template<>
struct DataType< ::motor_node::VelCommunicationRequest>
{
  static const char* value()
  {
    return DataType< ::motor_node::VelCommunication >::value();
  }
  static const char* value(const ::motor_node::VelCommunicationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motor_node::VelCommunicationResponse> should match
// service_traits::MD5Sum< ::motor_node::VelCommunication >
template<>
struct MD5Sum< ::motor_node::VelCommunicationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motor_node::VelCommunication >::value();
  }
  static const char* value(const ::motor_node::VelCommunicationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motor_node::VelCommunicationResponse> should match
// service_traits::DataType< ::motor_node::VelCommunication >
template<>
struct DataType< ::motor_node::VelCommunicationResponse>
{
  static const char* value()
  {
    return DataType< ::motor_node::VelCommunication >::value();
  }
  static const char* value(const ::motor_node::VelCommunicationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTOR_NODE_MESSAGE_VELCOMMUNICATION_H
