// Generated by gencpp from file motor_node/VelCommunicationResponse.msg
// DO NOT EDIT!


#ifndef MOTOR_NODE_MESSAGE_VELCOMMUNICATIONRESPONSE_H
#define MOTOR_NODE_MESSAGE_VELCOMMUNICATIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_node
{
template <class ContainerAllocator>
struct VelCommunicationResponse_
{
  typedef VelCommunicationResponse_<ContainerAllocator> Type;

  VelCommunicationResponse_()
    : result(false)  {
    }
  VelCommunicationResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::motor_node::VelCommunicationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_node::VelCommunicationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct VelCommunicationResponse_

typedef ::motor_node::VelCommunicationResponse_<std::allocator<void> > VelCommunicationResponse;

typedef boost::shared_ptr< ::motor_node::VelCommunicationResponse > VelCommunicationResponsePtr;
typedef boost::shared_ptr< ::motor_node::VelCommunicationResponse const> VelCommunicationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_node::VelCommunicationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_node::VelCommunicationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motor_node::VelCommunicationResponse_<ContainerAllocator1> & lhs, const ::motor_node::VelCommunicationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motor_node::VelCommunicationResponse_<ContainerAllocator1> & lhs, const ::motor_node::VelCommunicationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motor_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::motor_node::VelCommunicationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_node::VelCommunicationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_node::VelCommunicationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_node::VelCommunicationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_node::VelCommunicationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_node::VelCommunicationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_node::VelCommunicationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::motor_node::VelCommunicationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_node::VelCommunicationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_node/VelCommunicationResponse";
  }

  static const char* value(const ::motor_node::VelCommunicationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_node::VelCommunicationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n"
;
  }

  static const char* value(const ::motor_node::VelCommunicationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_node::VelCommunicationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VelCommunicationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_node::VelCommunicationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_node::VelCommunicationResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_NODE_MESSAGE_VELCOMMUNICATIONRESPONSE_H
