// Generated by gencpp from file motor_node/VelCommunicationRequest.msg
// DO NOT EDIT!


#ifndef MOTOR_NODE_MESSAGE_VELCOMMUNICATIONREQUEST_H
#define MOTOR_NODE_MESSAGE_VELCOMMUNICATIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_node
{
template <class ContainerAllocator>
struct VelCommunicationRequest_
{
  typedef VelCommunicationRequest_<ContainerAllocator> Type;

  VelCommunicationRequest_()
    : a(0)  {
    }
  VelCommunicationRequest_(const ContainerAllocator& _alloc)
    : a(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::motor_node::VelCommunicationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_node::VelCommunicationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct VelCommunicationRequest_

typedef ::motor_node::VelCommunicationRequest_<std::allocator<void> > VelCommunicationRequest;

typedef boost::shared_ptr< ::motor_node::VelCommunicationRequest > VelCommunicationRequestPtr;
typedef boost::shared_ptr< ::motor_node::VelCommunicationRequest const> VelCommunicationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_node::VelCommunicationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_node::VelCommunicationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motor_node::VelCommunicationRequest_<ContainerAllocator1> & lhs, const ::motor_node::VelCommunicationRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motor_node::VelCommunicationRequest_<ContainerAllocator1> & lhs, const ::motor_node::VelCommunicationRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motor_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::motor_node::VelCommunicationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_node::VelCommunicationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_node::VelCommunicationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_node::VelCommunicationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_node::VelCommunicationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_node::VelCommunicationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_node::VelCommunicationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "019706110004b728d56d8baaa8e32797";
  }

  static const char* value(const ::motor_node::VelCommunicationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x019706110004b728ULL;
  static const uint64_t static_value2 = 0xd56d8baaa8e32797ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_node::VelCommunicationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_node/VelCommunicationRequest";
  }

  static const char* value(const ::motor_node::VelCommunicationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_node::VelCommunicationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 a\n"
;
  }

  static const char* value(const ::motor_node::VelCommunicationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_node::VelCommunicationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VelCommunicationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_node::VelCommunicationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_node::VelCommunicationRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_NODE_MESSAGE_VELCOMMUNICATIONREQUEST_H
